### ISSUE TITLE
Can this be added to https://tree-sitter.github.io/tree-sitter/

### ISSUE THREAD

**Issue by spdegabrielle** [6cdh/tree-sitter-racket#1]
Can this be added to https://tree-sitter.github.io/tree-sitter/

While GitHub started with Python, it looks like GitHub is open to adding code navigation facilities for different language: https://github.blog/2022-04-29-bringing-code-navigation-to-communities/

I’ve not read properly but it like the Racket grammar for tree-sitter that you made is the primary requirement?

Bw
Stephen

**Comment by 6cdh** [comment]
Yes. I'll open a pull request later.
I just read it. From the post, we need

* [x] a Racket tree-sitter grammar
* [x] tags query in file `tags.scm`
* [x] We can also provide highlight query for Github Racket highlight.

It sounds cool. I will try it. I hope it can be done in a few days.

**Comment by 6cdh** [comment]
It's on the official website now: https://tree-sitter.github.io/tree-sitter/

**Comment by spdegabrielle** [comment]
Thank you for doing this 👏😁

it would be great if you put a little update to your post on the Racket Discourse so others know!

https://racket.discourse.group/t/tree-sitter-racket/1026/2?u=spdegabrielle

**Comment by spdegabrielle** [comment]
Will you close or do you want me to?

**Comment by 6cdh** [comment]
You are free to close it.
