### ISSUE TITLE
Parse `#;(+ 1 2 3)` as comment

### ISSUE THREAD

**Issue by glyh** [6cdh/tree-sitter-racket#3]
As title, I'm using https://github.com/nvim-treesitter, right now it doesn't have this behavior.

**Comment by 6cdh** [comment]
Can't reproduce. The sexp comment was already processed both in parser and nvim queries. Make sure you have nvim-treesitter installed and configured correctly.

**Comment by glyh** [comment]
Yeah I just realize I didn't config it correctly, sorry for the noise.
